### ISSUE TITLE
.NET MAUI

### ISSUE THREAD

**Issue by nsmith1024** [v-hogood/OpenCvSdk#2]
I have some questions for you.

1. Does this work with .NET MAUI (Visual Studio .NET 8) cross platform?

2. Do you have a sample MAUI project that uses OpenCV for both Android and IOS in the same project?

3. Can packages OpenCvSDK.Android and OpenCVSdk.IOS work with the nuget package called "OpenCV" in .NET MAUI?

Thanks

**Comment by v-hogood** [comment]
I added a sample .NET 8 project that uses OpenCV for both Android and iOS:
https://github.com/v-hogood/OpenCvSamples/tree/master/ColorBlobDetection

The nuget packaged called "OpenCV" is quite old, from 2017 for OpenCV version 2.4.11:
https://www.nuget.org/packages/OpenCV
