### ISSUE TITLE
iOS bug, maybe update to dotnet 9.0?

### ISSUE THREAD

**Issue by Th3L0x** [v-hogood/OpenCvSdk#7]
Please could you help I really need this package working

Getting this error on dotnet 9.0 when try to load a model

(in dotnet 8.0 all this worked fine)

Message =
"Could not find the type 'ObjCRuntime.__Registrar__' in the assembly 'OpenCvSdk.iOS'."
Source =
"Microsoft.iOS"
StackTrace =
"   at ObjCRuntime.RegistrarHelper.GetMapEntry(String assemblyName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 105\n   at ObjCRuntime.RegistrarHelper.GetMapEntry(Assembly assembly) in /Users/builder/azdo/_work/1/s/xam…"
TargetSite =
MapInfo GetMapEntry(System.String)

also for tensorflow too

Message =
"Could not find the type 'ObjCRuntime.__Registrar__' in the assembly 'TensorFlowLite'."
Source =
"Microsoft.iOS"
StackTrace =
"   at ObjCRuntime.RegistrarHelper.GetMapEntry(String assemblyName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 105\n   at ObjCRuntime.RegistrarHelper.GetMapEntry(Assembly assembly) in /Users/builder/azdo/_work/1/s/xam…"

**Comment by Th3L0x** [comment]
Do you know what is this ObjCRuntime.Registrar ?

**Comment by Th3L0x** [comment]
[testopencv.zip](https://github.com/user-attachments/files/17850563/testopencv.zip)
Here is sample project I just created, could you check it please?

**Comment by v-hogood** [comment]
I'm not using dotnet 9.0 yet but have you tried opting out of the new default registrar?

https://github.com/xamarin/xamarin-macios/wiki/.NET-9-release-notes#type-registrar-managed-static-as-the-new-default

**Comment by v-hogood** [comment]
That's referenced from https://github.com/TobiasBuchholz/Plugin.Firebase/issues/372

**Comment by Th3L0x** [comment]
Yes, thank you it solved it, I found it at here:
  https://blog.ostebaronen.dk/2024/11/dotnet9-gotchas.html
